AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Research and Transport Agents with SQS Async Processing

Globals:
  Function:
    Runtime: python3.11
    Architectures:
      - x86_64
    Environment:
      Variables:
        S3_BUCKET: !Ref DataBucket

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  GoogleMapsApiKey:
    Type: String
    NoEcho: true
    Description: Google Maps API Key

  OpenAIApiKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key

  AnthropicApiKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: Anthropic API Key (optional)

  ImageTag:
    Type: String
    Default: latest
    Description: Docker image tag (git commit SHA or latest)

Resources:
  # ========== S3 BUCKET ==========
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'retrieval-agent-data-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          # Clean up old object versions (safe for SQS)
          - Id: CleanupOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90  # Extended from 30 to 90 days
            Filter:
              Prefix: ""
          # Archive processed data (avoid active processing paths)
          - Id: ArchiveProcessedData
            Status: Enabled
            Filter:
              Prefix: processed/  # Only apply to processed data
            Transitions:
              - Days: 30
                StorageClass: STANDARD_IA
              - Days: 90
                StorageClass: GLACIER
            ExpirationInDays: 2555  # 7 years retention
          # Clean up temporary/working files (separate from main data)
          - Id: CleanupTempFiles
            Status: Enabled
            Filter:
              Prefix: temp/
            ExpirationInDays: 7
          # Manage logs separately (avoid interference with data processing)
          - Id: ManageLogs
            Status: Enabled
            Filter:
              Prefix: logs/
            Transitions:
              - Days: 30
                StorageClass: STANDARD_IA
              - Days: 90
                StorageClass: GLACIER
            ExpirationInDays: 365
          # Clean up incomplete multipart uploads
          - Id: CleanupIncompleteUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ========== SQS QUEUES FOR RESEARCH AGENT ==========
  ResearchTaskQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'research-tasks-${Environment}'
      VisibilityTimeout: 960  # 16 minutes
      MessageRetentionPeriod: 345600  # 4 days
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ResearchTaskDLQ.Arn
        maxReceiveCount: 3

  ResearchTaskDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'research-tasks-dlq-${Environment}'
      MessageRetentionPeriod: 1209600  # 14 days

  # ========== SQS QUEUES FOR TRANSPORT AGENT ==========
  TransportTaskQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'transport-tasks-${Environment}'
      VisibilityTimeout: 960  # 16 minutes
      MessageRetentionPeriod: 345600  # 4 days
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TransportTaskDLQ.Arn
        maxReceiveCount: 3

  TransportTaskDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'transport-tasks-dlq-${Environment}'
      MessageRetentionPeriod: 1209600  # 14 days

  # ========== IAM ROLES ==========
  # Research Queue Handler Role
  ResearchQueueHandlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'research-queue-handler-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ResearchQueueHandlerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                  - sqs:GetQueueAttributes
                Resource: !GetAtt ResearchTaskQueue.Arn
              - Effect: Allow
                Action:
                  - s3:HeadObject
                  - s3:GetObject
                Resource: !Sub '${DataBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub '${DataBucket.Arn}/*/status/*'

  # Research Processor Role
  ResearchProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'research-processor-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ResearchProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt ResearchTaskQueue.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub '${DataBucket.Arn}/*'

  # Transport Queue Handler Role
  TransportQueueHandlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'transport-queue-handler-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TransportQueueHandlerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                  - sqs:GetQueueAttributes
                Resource: !GetAtt TransportTaskQueue.Arn
              - Effect: Allow
                Action:
                  - s3:HeadObject
                  - s3:GetObject
                Resource: !Sub '${DataBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub '${DataBucket.Arn}/*/status/*'

  # Transport Processor Role
  TransportProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'transport-processor-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TransportProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt TransportTaskQueue.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub '${DataBucket.Arn}/*'

  # Status Checker Role (shared)
  StatusCheckerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'status-checker-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: StatusCheckerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub '${DataBucket.Arn}/*/status/*'

  # ========== SQS ACCESS POLICIES ==========
  ResearchQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ResearchTaskQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt ResearchTaskQueue.Arn

  TransportQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref TransportTaskQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt TransportTaskQueue.Arn

  # ResearchAgent Lambda Function
  ResearchAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'research-agent-${Environment}'
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/retrieval-agent:research-${ImageTag}'
      Role: !Ref LambdaExecutionRoleArn
      ImageConfig:
        Command:
          - lambda_handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          GOOGLE_MAPS_API_KEY: !Ref GoogleMapsApiKey
          OPENAI_API_KEY: !Ref OpenAIApiKey
          CLIMATIQ_API_KEY: !Ref ClimatiqApiKey
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /research
            Method: POST
            RestApiId: !Ref ApiGateway

  # TransportAgent Lambda Function
  TransportAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'transport-agent-${Environment}'
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/retrieval-agent:transport-${ImageTag}'
      Role: !Ref LambdaExecutionRoleArn
      ImageConfig:
        Command:
          - lambda_handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          GOOGLE_MAPS_API_KEY: !Ref GoogleMapsApiKey
          OPENAI_API_KEY: !Ref OpenAIApiKey
          CLIMATIQ_API_KEY: !Ref ClimatiqApiKey
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /transport
            Method: POST
            RestApiId: !Ref ApiGateway

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'retrieval-agent-api-${Environment}'
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'POST, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: Retrieval Agent API
          version: 1.0.0
          description: !Sub 'Deployed at ${DeploymentTimestamp} | Commit: ${ImageTag}'  # Force redeployment by changing API definition
        components:
          securitySchemes:
            api_key:
              type: apiKey
              name: x-api-key
              in: header
        security:
          - api_key: []
        paths:
          /research:
            post:
              summary: Research attractions and food places
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      required:
                        - input_s3_key
                        - output_s3_key
                      properties:
                        input_s3_key:
                          type: string
                          description: S3 key for input file
                        output_s3_key:
                          type: string
                          description: S3 key for output file
                        s3_bucket:
                          type: string
                          description: S3 bucket name (optional)
              responses:
                '200':
                  description: Success
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          message:
                            type: string
                          summary:
                            type: object
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResearchAgentFunction.Arn}/invocations'
          /transport:
            post:
              summary: Calculate transport options and carbon emissions
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      required:
                        - input_s3_key
                        - output_s3_key
                      properties:
                        input_s3_key:
                          type: string
                          description: S3 key for input file (output from research)
                        output_s3_key:
                          type: string
                          description: S3 key for output file
                        s3_bucket:
                          type: string
                          description: S3 bucket name (optional)
              responses:
                '200':
                  description: Success
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          message:
                            type: string
                          summary:
                            type: object
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TransportAgentFunction.Arn}/invocations'

  # API Key
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub 'retrieval-agent-key-${Environment}'
      Description: API Key for Retrieval Agent
      Enabled: true

  # Usage Plan
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ApiGatewayStage
    Properties:
      UsagePlanName: !Sub 'retrieval-agent-plan-${Environment}'
      Description: Usage plan for Retrieval Agent API
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: !Ref Environment
      Quota:
        Limit: 1000
        Period: MONTH
      Throttle:
        BurstLimit: 10
        RateLimit: 5

  # Link API Key to Usage Plan
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'

  ApiKey:
    Description: API Key ID (use AWS Console to get value)
    Value: !Ref ApiKey
    Export:
      Name: !Sub '${AWS::StackName}-ApiKey'

  DataBucketName:
    Description: S3 bucket for data storage
    Value: !Ref DataBucket
    Export:
      Name: !Sub '${AWS::StackName}-DataBucket'

  ResearchAgentFunctionArn:
    Description: ResearchAgent Lambda Function ARN
    Value: !GetAtt ResearchAgentFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ResearchAgentArn'

  TransportAgentFunctionArn:
    Description: TransportAgent Lambda Function ARN
    Value: !GetAtt TransportAgentFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TransportAgentArn'
