AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Research and Transport Agents with SQS Async Processing

Globals:
  Function:
    Architectures:
      - x86_64
    Environment:
      Variables:
        S3_BUCKET: !Ref DataBucket

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  GoogleMapsApiKey:
    Type: String
    NoEcho: true
    Description: Google Maps API Key

  OpenAIApiKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key

  AnthropicApiKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: Anthropic API Key (optional)

  ImageTag:
    Type: String
    Default: latest
    Description: Docker image tag (git commit SHA or latest)

Resources:
  # ========== S3 BUCKET ==========
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'retrieval-agent-data-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          # Clean up old object versions (safe for SQS)
          - Id: CleanupOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
          # Archive processed data (avoid active processing paths)
          - Id: ArchiveProcessedData
            Status: Enabled
            Prefix: processed/
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 2555
          # Clean up temporary/working files (separate from main data)
          - Id: CleanupTempFiles
            Status: Enabled
            Prefix: temp/
            ExpirationInDays: 7
          # Manage logs separately (avoid interference with data processing)
          - Id: ManageLogs
            Status: Enabled
            Prefix: logs/
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 365
          # Clean up incomplete multipart uploads
          - Id: CleanupIncompleteUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ========== SQS QUEUES FOR RESEARCH AGENT ==========
  ResearchTaskQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'research-tasks-${Environment}'
      VisibilityTimeout: 960  # 16 minutes
      MessageRetentionPeriod: 345600  # 4 days
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ResearchTaskDLQ.Arn
        maxReceiveCount: 3

  ResearchTaskDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'research-tasks-dlq-${Environment}'
      MessageRetentionPeriod: 1209600  # 14 days

  # ========== SQS QUEUES FOR TRANSPORT AGENT ==========
  TransportTaskQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'transport-tasks-${Environment}'
      VisibilityTimeout: 960  # 16 minutes
      MessageRetentionPeriod: 345600  # 4 days
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TransportTaskDLQ.Arn
        maxReceiveCount: 3

  TransportTaskDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'transport-tasks-dlq-${Environment}'
      MessageRetentionPeriod: 1209600  # 14 days

  # ========== IAM ROLES ==========
  # Research Queue Handler Role
  ResearchQueueHandlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'research-queue-handler-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ResearchQueueHandlerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                  - sqs:GetQueueAttributes
                Resource: !GetAtt ResearchTaskQueue.Arn
              - Effect: Allow
                Action:
                  - s3:HeadObject
                  - s3:GetObject
                Resource: !Sub '${DataBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub '${DataBucket.Arn}/*/status/*'
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                Resource: !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/retrieval-agent'
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'

  # Research Agent Role
  ResearchAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'research-agent-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ResearchAgentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt ResearchTaskQueue.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub '${DataBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                Resource: !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/retrieval-agent'
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'

  # Transport Queue Handler Role
  TransportQueueHandlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'transport-queue-handler-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TransportQueueHandlerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                  - sqs:GetQueueAttributes
                Resource: !GetAtt TransportTaskQueue.Arn
              - Effect: Allow
                Action:
                  - s3:HeadObject
                  - s3:GetObject
                Resource: !Sub '${DataBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub '${DataBucket.Arn}/*/status/*'
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                Resource: !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/retrieval-agent'
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'

  # Transport Agent Role
  TransportAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'transport-agent-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TransportAgentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt TransportTaskQueue.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub '${DataBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                Resource: !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/retrieval-agent'
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'

  # Status Checker Role
  StatusCheckerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'status-checker-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: StatusCheckerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub '${DataBucket.Arn}/*/status/*'
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                Resource: !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/retrieval-agent'
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'

  # ========== SQS ACCESS POLICIES ==========
  ResearchQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ResearchTaskQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt ResearchTaskQueue.Arn

  TransportQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref TransportTaskQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt TransportTaskQueue.Arn

  # ========== LAMBDA FUNCTIONS ==========
  # Research Agent Functions
  ResearchQueueHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'research-queue-handler-${Environment}'
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/retrieval-agent:research-${ImageTag}'
      Role: !GetAtt ResearchQueueHandlerRole.Arn
      Timeout: 60
      MemorySize: 1024
      ImageConfig:
        Command: ["queue_handler.lambda_handler"]
      Environment:
        Variables:
          QUEUE_URL: !Ref ResearchTaskQueue
          AGENT_TYPE: research
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /research
            Method: POST
            RestApiId: !Ref ApiGateway

  ResearchAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'research-agent-${Environment}'
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/retrieval-agent:research-${ImageTag}'
      Role: !GetAtt ResearchAgentRole.Arn
      Timeout: 900
      MemorySize: 3008
      ImageConfig:
        Command: ["sqs_processor.lambda_handler"]
      Environment:
        Variables:
          GOOGLE_MAPS_API_KEY: !Ref GoogleMapsApiKey
          OPENAI_API_KEY: !Ref OpenAIApiKey
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          AGENT_TYPE: research
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ResearchTaskQueue.Arn
            BatchSize: 1

  # Transport Agent Functions
  TransportQueueHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'transport-queue-handler-${Environment}'
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/retrieval-agent:transport-${ImageTag}'
      Role: !GetAtt TransportQueueHandlerRole.Arn
      Timeout: 60
      MemorySize: 1024
      ImageConfig:
        Command: ["queue_handler.lambda_handler"]
      Environment:
        Variables:
          QUEUE_URL: !Ref TransportTaskQueue
          AGENT_TYPE: transport
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /transport
            Method: POST
            RestApiId: !Ref ApiGateway

  TransportAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'transport-agent-${Environment}'
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/retrieval-agent:transport-${ImageTag}'
      Role: !GetAtt TransportAgentRole.Arn
      Timeout: 900
      MemorySize: 3008
      ImageConfig:
        Command: ["transport_processor.lambda_handler"]  # Different handler for transport
      Environment:
        Variables:
          GOOGLE_MAPS_API_KEY: !Ref GoogleMapsApiKey
          OPENAI_API_KEY: !Ref OpenAIApiKey
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          AGENT_TYPE: transport
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TransportTaskQueue.Arn
            BatchSize: 1

  # SHARED STATUS CHECKER
  # Uses research-agent image since status_handler is available in both research and transport images
  # We choose research-agent for consistency as it's the primary agent
  StatusCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'status-checker-${Environment}'
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/retrieval-agent:research-${ImageTag}'
      Role: !GetAtt StatusCheckerRole.Arn
      Timeout: 30
      MemorySize: 256
      ImageConfig:
        Command: ["lambda_handler.status_handler"]
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /status
            Method: POST
            RestApiId: !Ref ApiGateway

  # ========== API GATEWAY ==========
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'retrieval-agent-api-${Environment}'
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"
      Auth:
        ApiKeyRequired: true
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 50

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - ApiGatewayStage  # SAM-generated implicit stage resource
    Properties:
      Name: !Sub 'retrieval-agent-key-${Environment}'
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ApiGatewayStage  # SAM-generated implicit stage resource
    Properties:
      UsagePlanName: !Sub 'retrieval-agent-plan-${Environment}'
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: !Ref Environment
      Quota:
        Limit: 10000
        Period: MONTH
      Throttle:
        BurstLimit: 100
        RateLimit: 50

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  # ========== CLOUDWATCH ALARMS ==========
  ResearchDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'research-dlq-messages-${Environment}'
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ResearchTaskDLQ.QueueName

  TransportDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'transport-dlq-messages-${Environment}'
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt TransportTaskDLQ.QueueName

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'

  ResearchQueueUrl:
    Description: Research SQS Queue URL
    Value: !Ref ResearchTaskQueue

  TransportQueueUrl:
    Description: Transport SQS Queue URL
    Value: !Ref TransportTaskQueue

  ApiKeyId:
    Description: API Key ID
    Value: !Ref ApiKey

  S3Bucket:
    Description: S3 Bucket
    Value: !Ref DataBucket